### ISSUE TITLE
Blows up on emacs 27.2 presumably due to stand-alone hierarchy being deprecated

### ISSUE THREAD

**Issue by peterhoeg** [ahungry/md4rd#32]
Trying to run `(md4rd)` blows up with `require: Symbol’s value as variable is void: hierarchy--make`

Tried both the build from melpa and most recent commit on master.

Would this be due to hierarchy now being part of emacs?

**Comment by ahungry** [comment]
This works for me in 28.0.5, I'm not sure this error is enough for me to do anything with.

**Comment by mgcyung** [comment]
I encounterred the same problem and solved it by reinstalling md4rd and hierarchy.

**Comment by seblemaguer** [comment]
Depending on how it is installed, it could be due to the dependency declaration. On my side, I am using the couple (use-package, straight). When I retrieve the package `md4rd`, it also retrieves an older version of  `hierarchy`. This last one creates a conflict with the one which is available from emacs-core.

my solution consisted of manually edit the `Package-Requires:` section from md4rd and delete the "duplicate" version of `hierarchy`. It is ugly to do it this way, but I also think it is too early to remove the explicit dependency.

All in all, I just wanted to indicate this in case someone faces the same problem. Sorry for the lack of proper solution

**Comment by jladdjr** [comment]
Following up on @seblemaguer 's comment, I did some digging in my setup (in which I use `straight` and `use-package`) and noticed that `.emacs.d/straight/repos/melpa/recipes/hierarchy` seems to point to the older version of the hierarchy package:

`(hierarchy :fetcher github :repo "DamienCassou/hierarchy")`

Removing this file locally cleared up the issues I was running into (in my case json-navigator failed to load when it tried to load the hierarchy package).

With the hierarchy package being included in core Emacs, I'm wondering if this file should still be present:
https://github.com/melpa/melpa/blob/master/recipes/hierarchy

Or, perhaps it does still need to be present for older versions of Emacs, but should be flagged as such? (not sure how melpa handles versioning like this).
